### ISSUE TITLE
邀请码都木得了

### ISSUE THREAD

**Issue by MRdoulestar** [h4ckdepy/SeveTools#1]

**Comment by h4ckdepy** [comment]
啊  抱歉... 不知道为啥注册人这么多,先让他们用一段时间吧,效果好的话会放下一批,而且最近也是忙着写新功能和知识采集,功能欠缺的地方还是有很多55555。

**Comment by h4ckdepy** [comment]
下一批还是会发的,并且永久公益免费。等项目的耦合度降低和接口、文档的生态趋于完善,就会考虑平台开源！谢谢各位支持。
